FROM wimmercg/lazarus-docker:1.1.0
#FROM  lazarus-base

LABEL Name="FCP Source and Lazarus Git main, Linux64 and Win32, Win64 crosscompile with lazbuild" 

RUN apt update && apt install subversion -y
RUN mkdir /build && mkdir source && mkdir -p /temp

RUN git clone https://github.com/PascalCorpsman/fpc_atomic.git /source/fpc_atomic
RUN wget https://www.un4seen.com/files/bass24.zip && unzip -j bass24.zip x64/bass.dll -d /temp && unzip -j bass24.zip delphi/bass.pas -d /source/fpc_atomic
RUN mkdir -p /source/fpc_atomic/lib/x86_64-linux && wget https://www.un4seen.com/files/bass24-linux.zip && unzip -j bass24-linux.zip libs/x86_64/libbass.so -d /source/fpc_atomic/

RUN wget https://raw.githubusercontent.com/SaschaWillems/dglOpenGL/master/dglOpenGL.pas -O /source/fpc_atomic/dglOpenGL.pas

RUN mkdir -p /source/synapse && cd /source/synapse && svn checkout https://svn.code.sf.net/p/synalist/code/trunk . && mv /source/synapse/* /source/fpc_atomic/

# build linux 64
RUN echo "cd /source/fpc_atomic/ && lazbuildl64 fpc_atomic.lpi && mv fpc_atomic /build" > /bl.sh && chmod 777 /bl.sh

#RUN cd $LAZARUSDIR && ./lazbuild --add-package /source/synapse/laz_synapse.lpk --primary-config-path=$LAZARUSDIR --lazarusdir=$LAZARUSDIR
RUN echo "URL_CheckForUpdate = '';" > /source/fpc_atomic/updater_link.inc

RUN /install_corpsman_lnet.sh



COPY runenv.sh /runenv.sh
RUN chmod 777 /runenv.sh

CMD /runenv.sh