version: '3.4'

services:
  atomic:
    image: atomic
    volumes:
      - /d/Projekte/fpc_atomic/bomber/:/AtomicGameRoot
      - ${PWD}/build:/build
    tty: true
    stdin_open: true
    environment:
      - ATOMIC_BUILD_WIN64=true
      - ATOMIC_BUILD_WIN32=true
      - ATOMIC_BUILD_LINUX=true
      - ATOMIC_EXTRA_ANI=true
