#!/bin/bash
# Script to deploy FPC Atomic Server to Fly.io using pre-built Docker image + game data
# This script creates a custom Dockerfile that uses the base image and adds game data
# Works on macOS, Linux, and Windows (with Git Bash or WSL)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
FLYIO_DIR="${SCRIPT_DIR}"

# Default base image
BASE_IMAGE="${BASE_IMAGE:-ghcr.io/PavelZverina/fpc-atomic-server:latest}"

echo "========================================="
echo "Deploying FPC Atomic Server to Fly.io"
echo "Using pre-built image + game data"
echo "========================================="
echo ""

# Check if flyctl is installed
if ! command -v flyctl &> /dev/null; then
  echo "Error: flyctl is not installed" >&2
  echo "Please install it using:" >&2
  echo "  curl -L https://fly.io/install.sh | sh" >&2
  exit 1
fi

# Check if Docker is installed (needed for local build)
if ! command -v docker &> /dev/null; then
  echo "Error: Docker is not installed" >&2
  echo "This script requires Docker to build a custom image with game data." >&2
  echo "Please install Docker Desktop or Docker Engine." >&2
  exit 1
fi

# Check if data directory exists
if [[ ! -d "${FLYIO_DIR}/data" ]]; then
  echo "========================================="
  echo "⚠️  ERROR: Game data directory not found!"
  echo "========================================="
  echo ""
  echo "This script requires game data to be present."
  echo ""
  echo "To add game data:"
  echo "  1. Extract data from the original Atomic Bomberman CD"
  echo "     using the CD Data Extractor tool"
  echo "  2. Copy the extracted 'data' directory to:"
  echo "     ${FLYIO_DIR}/data"
  echo ""
  echo "The data directory should contain:"
  echo "  - maps/ (game maps)"
  echo "  - res/ (resources, textures, etc.)"
  echo "  - sounds/ (sound effects)"
  echo ""
  
  # Check if data exists in project root as alternative
  if [[ -d "${PROJECT_ROOT}/data" ]]; then
    echo "Found data directory in project root: ${PROJECT_ROOT}/data"
    read -p "Copy it to flyio_server/data? (y/N) " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
      echo "Copying data directory..."
      cp -r "${PROJECT_ROOT}/data" "${FLYIO_DIR}/data"
      echo "✓ Data directory copied"
    else
      echo "Deployment cancelled."
      exit 1
    fi
  else
    echo "Deployment cancelled. Please add game data first."
    exit 1
  fi
else
  echo "✓ Game data directory found at ${FLYIO_DIR}/data"
fi

# Verify data directory has required content
if [[ ! -d "${FLYIO_DIR}/data/maps" ]]; then
  echo "Warning: data/maps directory not found. Server will work but without game maps." >&2
fi

# Create temporary Dockerfile that uses base image + adds data
TEMP_DOCKERFILE="${FLYIO_DIR}/Dockerfile.with_data"
cat > "${TEMP_DOCKERFILE}" << EOF
# Temporary Dockerfile for deployment with game data
# This file is auto-generated by deploy_with_data.sh
# It uses the pre-built base image and adds game data

FROM ${BASE_IMAGE}

# Copy game data into the image
COPY data /app/data

# The base image already has the server binary and all dependencies
# We just need to add the game data
EOF

echo ""
echo "Created temporary Dockerfile: ${TEMP_DOCKERFILE}"
echo "Base image: ${BASE_IMAGE}"
echo ""

# Create temporary fly.toml that uses the Dockerfile
TEMP_FLY_TOML="${FLYIO_DIR}/fly.toml.with_data"
cat > "${TEMP_FLY_TOML}" << EOF
# Temporary fly.toml for deployment with game data
# This file is auto-generated by deploy_with_data.sh

app = "fpc-atomic-tcp-server"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile.with_data"
  build_args = {}

[deploy]
  strategy = "immediate"

[env]
  PORT = "5521"

[[services]]
  protocol = "tcp"
  internal_port = 5521
  processes = ["app"]
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 5521

  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 50

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "10s"
    grace_period = "45s"
    restart_limit = 6
EOF

echo "Created temporary fly.toml: ${TEMP_FLY_TOML}"
echo ""

# Change to flyio_server directory (build context will be this directory)
cd "${FLYIO_DIR}"

echo "Build context: ${FLYIO_DIR}"
echo "Dockerfile: ${TEMP_DOCKERFILE}"
echo ""

# Deploy to Fly.io
echo "Starting deployment with game data..."
flyctl deploy --config "${TEMP_FLY_TOML}" "$@"

# Cleanup temporary files
echo ""
echo "Cleaning up temporary files..."
rm -f "${TEMP_DOCKERFILE}" "${TEMP_FLY_TOML}"

echo ""
echo "========================================="
echo "Deployment complete!"
echo "========================================="
echo ""
echo "To check server status:"
echo "  flyctl status --config ${FLYIO_DIR}/fly.toml"
echo ""
echo "To view logs:"
echo "  flyctl logs --config ${FLYIO_DIR}/fly.toml"
echo ""
