''Eval Image with http://plantuml.sourceforge.net/
''---------- Server_states.png ---------- 
@startuml

Title Server States

(*) --> "gsWaitForPlayersToConnect"
"gsWaitForPlayersToConnect" --> "gsPlayerSetup" 
"gsPlayerSetup" --> "gsMapSetup"
"gsMapSetup" --> "gsPlaying"
"gsPlaying" --> "gsShowHighscore"
"gsShowHighscore" --> "gsWaitForPlayersToConnect"
"gsWaitForPlayersToConnect" --> (*)
@enduml
